"""empty message

Revision ID: 6c08b9117f37
Revises: 
Create Date: 2020-09-26 16:27:33.810171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c08b9117f37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'day',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('bookings', 'time',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'time',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bookings', 'day',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
